package msgs
type WebcastSubNotifyMessage struct {
	IsCustom bool `json:"isCustom"`
	User struct {
		Deprecated8 float64 `json:"deprecated8"`
		FollowInfo struct {
			FollowingCount string `json:"followingCount"`
			FollowerCount string `json:"followerCount"`
			FollowStatus string `json:"followStatus"`
			PushStatus string `json:"pushStatus"`
		} `json:"followInfo"`
		AllowStrangeComment bool `json:"allowStrangeComment"`
		Deprecated28 bool `json:"deprecated28"`
		Deprecated29 string `json:"deprecated29"`
		SecUid string `json:"secUid"`
		UserRole float64 `json:"userRole"`
		Deprecated12 float64 `json:"deprecated12"`
		Deprecated1 string `json:"deprecated1"`
		Deprecated2 float64 `json:"deprecated2"`
		Deprecated7 string `json:"deprecated7"`
		LinkMicStats float64 `json:"linkMicStats"`
		Deprecated21 string `json:"deprecated21"`
		Deprecated15 float64 `json:"deprecated15"`
		BgImgUrl string `json:"bgImgUrl"`
		DisableIchat float64 `json:"disableIchat"`
		AllowShareShowProfile bool `json:"allowShareShowProfile"`
		Deprecated18 string `json:"deprecated18"`
		Exp float64 `json:"exp"`
		IsBlock bool `json:"isBlock"`
		AvatarThumb struct {
			AvgColor string `json:"avgColor"`
			ImageType float64 `json:"imageType"`
			OpenWebUrl string `json:"openWebUrl"`
			IsAnimated bool `json:"isAnimated"`
			UrlListList []string `json:"urlListList"`
			Uri string `json:"uri"`
			Height string `json:"height"`
			Width string `json:"width"`
		} `json:"avatarThumb"`
		AllowShowMyAction bool `json:"allowShowMyAction"`
		Constellation string `json:"constellation"`
		EnableIchatImg string `json:"enableIchatImg"`
		FollowStatus string `json:"followStatus"`
		WithCarManagementPermission bool `json:"withCarManagementPermission"`
		PushCommentStatus bool `json:"pushCommentStatus"`
		PushStatus bool `json:"pushStatus"`
		Deprecated17 bool `json:"deprecated17"`
		BioDescription string `json:"bioDescription"`
		ModifyTime string `json:"modifyTime"`
		ShareQrcodeUri string `json:"shareQrcodeUri"`
		AllowUseLinkmic bool `json:"allowUseLinkmic"`
		Deprecated3 float64 `json:"deprecated3"`
		SpecialId string `json:"specialId"`
		Deprecated13 float64 `json:"deprecated13"`
		IdStr string `json:"idStr"`
		IsFollower bool `json:"isFollower"`
		AllowShowInGossip bool `json:"allowShowInGossip"`
		AllowUnfollowerComment bool `json:"allowUnfollowerComment"`
		FoldStrangerChat bool `json:"foldStrangerChat"`
		WithCommercePermission bool `json:"withCommercePermission"`
		AllowFindByContacts bool `json:"allowFindByContacts"`
		IchatRestrictType float64 `json:"ichatRestrictType"`
		PushVideoRecommend bool `json:"pushVideoRecommend"`
		Deprecated16 bool `json:"deprecated16"`
		CommentRestrict float64 `json:"commentRestrict"`
		PushFollow bool `json:"pushFollow"`
		VerifiedReason string `json:"verifiedReason"`
		PushFriendAction bool `json:"pushFriendAction"`
		ScmLabel string `json:"scmLabel"`
		Nickname string `json:"nickname"`
		Deprecated5 string `json:"deprecated5"`
		TopVipNo string `json:"topVipNo"`
		UserAttr struct {
			IsMuted bool `json:"isMuted"`
			IsAdmin bool `json:"isAdmin"`
			IsSuperAdmin bool `json:"isSuperAdmin"`
			MuteDuration string `json:"muteDuration"`
		} `json:"userAttr"`
		Verified bool `json:"verified"`
		PayScore string `json:"payScore"`
		AllowOthersDownloadWhenSharingVideo bool `json:"allowOthersDownloadWhenSharingVideo"`
		BlockStatus float64 `json:"blockStatus"`
		PushVideoPost bool `json:"pushVideoPost"`
		Id string `json:"id"`
		DisplayId string `json:"displayId"`
		VerifiedContent string `json:"verifiedContent"`
		Deprecated19 bool `json:"deprecated19"`
		AllowOthersDownloadVideo bool `json:"allowOthersDownloadVideo"`
		FanTicketCount string `json:"fanTicketCount"`
		NeedProfileGuide bool `json:"needProfileGuide"`
		PushDigg bool `json:"pushDigg"`
		IsFollowing bool `json:"isFollowing"`
		PayScores string `json:"payScores"`
		Status float64 `json:"status"`
		CreateTime string `json:"createTime"`
		WithFusionShopEntry bool `json:"withFusionShopEntry"`
		Deprecated4 string `json:"deprecated4"`
		Deprecated6 float64 `json:"deprecated6"`
		Secret float64 `json:"secret"`
		TicketCount string `json:"ticketCount"`
		PushIchat bool `json:"pushIchat"`
	} `json:"user"`
	SubscribingStatus float64 `json:"subscribingStatus"`
	IsSend bool `json:"isSend"`
	SubscribeType float64 `json:"subscribeType"`
	OldSubscribeStatus float64 `json:"oldSubscribeStatus"`
	MessageType float64 `json:"messageType"`
	Common struct {
		ClientSendTime string `json:"clientSendTime"`
		DispatchStrategy float64 `json:"dispatchStrategy"`
		Method string `json:"method"`
		MsgId string `json:"msgId"`
		DisplayText struct {
			PiecesList []*struct {
				StringValue string `json:"stringValue"`
				UserValue struct {
					User struct {
						Deprecated2 float64 `json:"deprecated2"`
						Deprecated7 string `json:"deprecated7"`
						TopVipNo string `json:"topVipNo"`
						PayScore string `json:"payScore"`
						SecUid string `json:"secUid"`
						Deprecated6 float64 `json:"deprecated6"`
						Secret float64 `json:"secret"`
						IsFollowing bool `json:"isFollowing"`
						PushFollow bool `json:"pushFollow"`
						ScmLabel string `json:"scmLabel"`
						ShareQrcodeUri string `json:"shareQrcodeUri"`
						UserRole float64 `json:"userRole"`
						Deprecated16 bool `json:"deprecated16"`
						DisableIchat float64 `json:"disableIchat"`
						VerifiedContent string `json:"verifiedContent"`
						Deprecated19 bool `json:"deprecated19"`
						AllowShareShowProfile bool `json:"allowShareShowProfile"`
						Deprecated18 string `json:"deprecated18"`
						IsFollower bool `json:"isFollower"`
						PushIchat bool `json:"pushIchat"`
						PushStatus bool `json:"pushStatus"`
						Id string `json:"id"`
						SpecialId string `json:"specialId"`
						Deprecated12 float64 `json:"deprecated12"`
						AllowShowMyAction bool `json:"allowShowMyAction"`
						Constellation string `json:"constellation"`
						PushVideoRecommend bool `json:"pushVideoRecommend"`
						FollowInfo struct {
							FollowStatus string `json:"followStatus"`
							PushStatus string `json:"pushStatus"`
							FollowingCount string `json:"followingCount"`
							FollowerCount string `json:"followerCount"`
						} `json:"followInfo"`
						Deprecated29 string `json:"deprecated29"`
						PushCommentStatus bool `json:"pushCommentStatus"`
						Status float64 `json:"status"`
						BgImgUrl string `json:"bgImgUrl"`
						FollowStatus string `json:"followStatus"`
						PushVideoPost bool `json:"pushVideoPost"`
						BioDescription string `json:"bioDescription"`
						TicketCount string `json:"ticketCount"`
						Deprecated21 string `json:"deprecated21"`
						Deprecated28 bool `json:"deprecated28"`
						IdStr string `json:"idStr"`
						Deprecated1 string `json:"deprecated1"`
						Deprecated8 float64 `json:"deprecated8"`
						AllowShowInGossip bool `json:"allowShowInGossip"`
						WithCommercePermission bool `json:"withCommercePermission"`
						WithFusionShopEntry bool `json:"withFusionShopEntry"`
						CommentRestrict float64 `json:"commentRestrict"`
						FanTicketCount string `json:"fanTicketCount"`
						PushDigg bool `json:"pushDigg"`
						DisplayId string `json:"displayId"`
						BlockStatus float64 `json:"blockStatus"`
						IchatRestrictType float64 `json:"ichatRestrictType"`
						VerifiedReason string `json:"verifiedReason"`
						AllowUnfollowerComment bool `json:"allowUnfollowerComment"`
						Exp float64 `json:"exp"`
						WithCarManagementPermission bool `json:"withCarManagementPermission"`
						CreateTime string `json:"createTime"`
						UserAttr struct {
							MuteDuration string `json:"muteDuration"`
							IsMuted bool `json:"isMuted"`
							IsAdmin bool `json:"isAdmin"`
							IsSuperAdmin bool `json:"isSuperAdmin"`
						} `json:"userAttr"`
						AllowFindByContacts bool `json:"allowFindByContacts"`
						IsBlock bool `json:"isBlock"`
						Nickname string `json:"nickname"`
						Deprecated13 float64 `json:"deprecated13"`
						PayScores string `json:"payScores"`
						PushFriendAction bool `json:"pushFriendAction"`
						Deprecated4 string `json:"deprecated4"`
						Deprecated5 string `json:"deprecated5"`
						Verified bool `json:"verified"`
						ModifyTime string `json:"modifyTime"`
						LinkMicStats float64 `json:"linkMicStats"`
						Deprecated15 float64 `json:"deprecated15"`
						AllowOthersDownloadWhenSharingVideo bool `json:"allowOthersDownloadWhenSharingVideo"`
						Deprecated3 float64 `json:"deprecated3"`
						AvatarThumb struct {
							OpenWebUrl string `json:"openWebUrl"`
							IsAnimated bool `json:"isAnimated"`
							UrlListList []string `json:"urlListList"`
							Uri string `json:"uri"`
							Height string `json:"height"`
							Width string `json:"width"`
							AvgColor string `json:"avgColor"`
							ImageType float64 `json:"imageType"`
						} `json:"avatarThumb"`
						AllowOthersDownloadVideo bool `json:"allowOthersDownloadVideo"`
						AllowStrangeComment bool `json:"allowStrangeComment"`
						AllowUseLinkmic bool `json:"allowUseLinkmic"`
						EnableIchatImg string `json:"enableIchatImg"`
						FoldStrangerChat bool `json:"foldStrangerChat"`
						NeedProfileGuide bool `json:"needProfileGuide"`
						Deprecated17 bool `json:"deprecated17"`
					} `json:"user"`
					WithColon bool `json:"withColon"`
				} `json:"userValue"`
				Type float64 `json:"type"`
			} `json:"piecesList"`
			Key string `json:"key"`
			DefaultPattern string `json:"defaultPattern"`
			DefaultFormat struct {
				Weight float64 `json:"weight"`
				ItalicAngle float64 `json:"italicAngle"`
				FontSize float64 `json:"fontSize"`
				UseHeighLightColor bool `json:"useHeighLightColor"`
				UseRemoteClor bool `json:"useRemoteClor"`
				Color string `json:"color"`
				Bold bool `json:"bold"`
				Italic bool `json:"italic"`
			} `json:"defaultFormat"`
		} `json:"displayText"`
		FoldType string `json:"foldType"`
		ToIdc string `json:"toIdc"`
		Monitor float64 `json:"monitor"`
		AnchorFoldTypeForWeb string `json:"anchorFoldTypeForWeb"`
		RoomMessageHeatLevel string `json:"roomMessageHeatLevel"`
		RoomId string `json:"roomId"`
		AnchorFoldType string `json:"anchorFoldType"`
		PriorityScore string `json:"priorityScore"`
		MsgProcessFilterV string `json:"msgProcessFilterV"`
		FromIdc string `json:"fromIdc"`
		AnchorPriorityScore string `json:"anchorPriorityScore"`
		FoldTypeForWeb string `json:"foldTypeForWeb"`
		CreateTime string `json:"createTime"`
		IsShowMsg bool `json:"isShowMsg"`
		Describe string `json:"describe"`
		LogId string `json:"logId"`
		MsgProcessFilterK string `json:"msgProcessFilterK"`
	} `json:"common"`
	ExhibitionType float64 `json:"exhibitionType"`
	SubMonth string `json:"subMonth"`
}
