package msgs
type WebcastLikeMessage struct {
	Common struct {
		MsgProcessFilterV string `json:"msgProcessFilterV"`
		MsgId string `json:"msgId"`
		FoldType string `json:"foldType"`
		Describe string `json:"describe"`
		PriorityScore string `json:"priorityScore"`
		LogId string `json:"logId"`
		MsgProcessFilterK string `json:"msgProcessFilterK"`
		RoomMessageHeatLevel string `json:"roomMessageHeatLevel"`
		AnchorFoldTypeForWeb string `json:"anchorFoldTypeForWeb"`
		RoomId string `json:"roomId"`
		CreateTime string `json:"createTime"`
		IsShowMsg bool `json:"isShowMsg"`
		DisplayText struct {
			Key string `json:"key"`
			DefaultPattern string `json:"defaultPattern"`
			DefaultFormat struct {
				UseHeighLightColor bool `json:"useHeighLightColor"`
				UseRemoteClor bool `json:"useRemoteClor"`
				Color string `json:"color"`
				Bold bool `json:"bold"`
				Italic bool `json:"italic"`
				Weight float64 `json:"weight"`
				ItalicAngle float64 `json:"italicAngle"`
				FontSize float64 `json:"fontSize"`
			} `json:"defaultFormat"`
			PiecesList []*struct {
				Type float64 `json:"type"`
				StringValue string `json:"stringValue"`
				UserValue struct {
					User struct {
						PushDigg bool `json:"pushDigg"`
						Nickname string `json:"nickname"`
						SpecialId string `json:"specialId"`
						AllowShowInGossip bool `json:"allowShowInGossip"`
						AllowShowMyAction bool `json:"allowShowMyAction"`
						IdStr string `json:"idStr"`
						IsFollowing bool `json:"isFollowing"`
						ModifyTime string `json:"modifyTime"`
						Deprecated21 string `json:"deprecated21"`
						Constellation string `json:"constellation"`
						AllowShareShowProfile bool `json:"allowShareShowProfile"`
						PushStatus bool `json:"pushStatus"`
						Deprecated1 string `json:"deprecated1"`
						ShareQrcodeUri string `json:"shareQrcodeUri"`
						Deprecated8 float64 `json:"deprecated8"`
						WithCommercePermission bool `json:"withCommercePermission"`
						BlockStatus float64 `json:"blockStatus"`
						PushIchat bool `json:"pushIchat"`
						TicketCount string `json:"ticketCount"`
						LinkMicStats float64 `json:"linkMicStats"`
						VerifiedContent string `json:"verifiedContent"`
						Deprecated15 float64 `json:"deprecated15"`
						EnableIchatImg string `json:"enableIchatImg"`
						PayScores string `json:"payScores"`
						BioDescription string `json:"bioDescription"`
						Deprecated18 string `json:"deprecated18"`
						WithCarManagementPermission bool `json:"withCarManagementPermission"`
						IsBlock bool `json:"isBlock"`
						Deprecated2 float64 `json:"deprecated2"`
						AllowOthersDownloadVideo bool `json:"allowOthersDownloadVideo"`
						Deprecated29 string `json:"deprecated29"`
						NeedProfileGuide bool `json:"needProfileGuide"`
						WithFusionShopEntry bool `json:"withFusionShopEntry"`
						BgImgUrl string `json:"bgImgUrl"`
						CommentRestrict float64 `json:"commentRestrict"`
						IchatRestrictType float64 `json:"ichatRestrictType"`
						PayScore string `json:"payScore"`
						SecUid string `json:"secUid"`
						PushVideoPost bool `json:"pushVideoPost"`
						VerifiedReason string `json:"verifiedReason"`
						AllowFindByContacts bool `json:"allowFindByContacts"`
						Exp float64 `json:"exp"`
						FanTicketCount string `json:"fanTicketCount"`
						FollowStatus string `json:"followStatus"`
						Deprecated19 bool `json:"deprecated19"`
						FoldStrangerChat bool `json:"foldStrangerChat"`
						Deprecated17 bool `json:"deprecated17"`
						Deprecated5 string `json:"deprecated5"`
						Deprecated6 float64 `json:"deprecated6"`
						CreateTime string `json:"createTime"`
						AllowUseLinkmic bool `json:"allowUseLinkmic"`
						DisableIchat float64 `json:"disableIchat"`
						PushFollow bool `json:"pushFollow"`
						PushFriendAction bool `json:"pushFriendAction"`
						Id string `json:"id"`
						Deprecated7 string `json:"deprecated7"`
						Secret float64 `json:"secret"`
						AllowUnfollowerComment bool `json:"allowUnfollowerComment"`
						UserRole float64 `json:"userRole"`
						Deprecated28 bool `json:"deprecated28"`
						IsFollower bool `json:"isFollower"`
						PushVideoRecommend bool `json:"pushVideoRecommend"`
						Verified bool `json:"verified"`
						Status float64 `json:"status"`
						Deprecated13 float64 `json:"deprecated13"`
						AllowStrangeComment bool `json:"allowStrangeComment"`
						AllowOthersDownloadWhenSharingVideo bool `json:"allowOthersDownloadWhenSharingVideo"`
						PushCommentStatus bool `json:"pushCommentStatus"`
						Deprecated3 float64 `json:"deprecated3"`
						TopVipNo string `json:"topVipNo"`
						DisplayId string `json:"displayId"`
						Deprecated12 float64 `json:"deprecated12"`
						ScmLabel string `json:"scmLabel"`
						Deprecated4 string `json:"deprecated4"`
						Deprecated16 bool `json:"deprecated16"`
					} `json:"user"`
					WithColon bool `json:"withColon"`
				} `json:"userValue"`
			} `json:"piecesList"`
		} `json:"displayText"`
		FromIdc string `json:"fromIdc"`
		ToIdc string `json:"toIdc"`
		ClientSendTime string `json:"clientSendTime"`
		Method string `json:"method"`
		Monitor float64 `json:"monitor"`
		DispatchStrategy float64 `json:"dispatchStrategy"`
		FoldTypeForWeb string `json:"foldTypeForWeb"`
		AnchorFoldType string `json:"anchorFoldType"`
		AnchorPriorityScore string `json:"anchorPriorityScore"`
	} `json:"common"`
	User struct {
		Deprecated1 string `json:"deprecated1"`
		DisplayId string `json:"displayId"`
		Deprecated21 string `json:"deprecated21"`
		Deprecated13 float64 `json:"deprecated13"`
		IsFollowing bool `json:"isFollowing"`
		BgImgUrl string `json:"bgImgUrl"`
		IsFollower bool `json:"isFollower"`
		PushCommentStatus bool `json:"pushCommentStatus"`
		Deprecated2 float64 `json:"deprecated2"`
		AllowUnfollowerComment bool `json:"allowUnfollowerComment"`
		FanTicketCount string `json:"fanTicketCount"`
		Deprecated17 bool `json:"deprecated17"`
		WithCarManagementPermission bool `json:"withCarManagementPermission"`
		PayGrade struct {
			Deprecated20 string `json:"deprecated20"`
			NextName string `json:"nextName"`
			GradeDescribe string `json:"gradeDescribe"`
			UpgradeNeedConsume string `json:"upgradeNeedConsume"`
			GradeBanner string `json:"gradeBanner"`
			Deprecated22 string `json:"deprecated22"`
			Deprecated23 string `json:"deprecated23"`
			Deprecated24 string `json:"deprecated24"`
			Deprecated26 string `json:"deprecated26"`
			NextPrivileges string `json:"nextPrivileges"`
			Name string `json:"name"`
			Level string `json:"level"`
			Deprecated25 string `json:"deprecated25"`
			ScreenChatType string `json:"screenChatType"`
			Score string `json:"score"`
		} `json:"payGrade"`
		AllowShowInGossip bool `json:"allowShowInGossip"`
		NeedProfileGuide bool `json:"needProfileGuide"`
		VerifiedReason string `json:"verifiedReason"`
		ScmLabel string `json:"scmLabel"`
		AllowShareShowProfile bool `json:"allowShareShowProfile"`
		BioDescription string `json:"bioDescription"`
		Deprecated5 string `json:"deprecated5"`
		TopVipNo string `json:"topVipNo"`
		UserRole float64 `json:"userRole"`
		AllowOthersDownloadWhenSharingVideo bool `json:"allowOthersDownloadWhenSharingVideo"`
		PushVideoRecommend bool `json:"pushVideoRecommend"`
		SecUid string `json:"secUid"`
		Deprecated19 bool `json:"deprecated19"`
		AllowUseLinkmic bool `json:"allowUseLinkmic"`
		Constellation string `json:"constellation"`
		DisableIchat float64 `json:"disableIchat"`
		EnableIchatImg string `json:"enableIchatImg"`
		Exp float64 `json:"exp"`
		FollowStatus string `json:"followStatus"`
		PushIchat bool `json:"pushIchat"`
		PushFollow bool `json:"pushFollow"`
		Deprecated8 float64 `json:"deprecated8"`
		Deprecated18 string `json:"deprecated18"`
		IchatRestrictType float64 `json:"ichatRestrictType"`
		PayScores string `json:"payScores"`
		IsBlock bool `json:"isBlock"`
		Deprecated6 float64 `json:"deprecated6"`
		Deprecated7 string `json:"deprecated7"`
		Secret float64 `json:"secret"`
		Deprecated16 bool `json:"deprecated16"`
		Deprecated28 bool `json:"deprecated28"`
		Deprecated3 float64 `json:"deprecated3"`
		CreateTime string `json:"createTime"`
		SpecialId string `json:"specialId"`
		CommentRestrict float64 `json:"commentRestrict"`
		PushDigg bool `json:"pushDigg"`
		Id string `json:"id"`
		TicketCount string `json:"ticketCount"`
		AllowFindByContacts bool `json:"allowFindByContacts"`
		AllowShowMyAction bool `json:"allowShowMyAction"`
		AllowStrangeComment bool `json:"allowStrangeComment"`
		BlockStatus float64 `json:"blockStatus"`
		PushVideoPost bool `json:"pushVideoPost"`
		Deprecated4 string `json:"deprecated4"`
		PayScore string `json:"payScore"`
		Deprecated15 float64 `json:"deprecated15"`
		AllowOthersDownloadVideo bool `json:"allowOthersDownloadVideo"`
		FoldStrangerChat bool `json:"foldStrangerChat"`
		Verified bool `json:"verified"`
		ShareQrcodeUri string `json:"shareQrcodeUri"`
		WithCommercePermission bool `json:"withCommercePermission"`
		AvatarThumb struct {
			IsAnimated bool `json:"isAnimated"`
			UrlListList []string `json:"urlListList"`
			Uri string `json:"uri"`
			Height string `json:"height"`
			Width string `json:"width"`
			AvgColor string `json:"avgColor"`
			ImageType float64 `json:"imageType"`
			OpenWebUrl string `json:"openWebUrl"`
		} `json:"avatarThumb"`
		WithFusionShopEntry bool `json:"withFusionShopEntry"`
		PushStatus bool `json:"pushStatus"`
		Nickname string `json:"nickname"`
		Status float64 `json:"status"`
		LinkMicStats float64 `json:"linkMicStats"`
		VerifiedContent string `json:"verifiedContent"`
		IdStr string `json:"idStr"`
		PushFriendAction bool `json:"pushFriendAction"`
		ModifyTime string `json:"modifyTime"`
		FollowInfo struct {
			FollowingCount string `json:"followingCount"`
			FollowerCount string `json:"followerCount"`
			FollowStatus string `json:"followStatus"`
			PushStatus string `json:"pushStatus"`
		} `json:"followInfo"`
		UserAttr struct {
			IsSuperAdmin bool `json:"isSuperAdmin"`
			MuteDuration string `json:"muteDuration"`
			IsMuted bool `json:"isMuted"`
			IsAdmin bool `json:"isAdmin"`
		} `json:"userAttr"`
		Deprecated12 float64 `json:"deprecated12"`
		BadgeListList []*struct {
			DisplayType float64 `json:"displayType"`
			PriorityType float64 `json:"priorityType"`
			Position float64 `json:"position"`
			GreyedByClient string `json:"greyedByClient"`
			ExhibitionType float64 `json:"exhibitionType"`
			Display bool `json:"display"`
			SceneType float64 `json:"sceneType"`
			DisplayStatus float64 `json:"displayStatus"`
			Openweburl string `json:"openweburl"`
			PrivilegeLogExtra struct {
				Level string `json:"level"`
				DataVersion string `json:"dataVersion"`
				PrivilegeId string `json:"privilegeId"`
				PrivilegeVersion string `json:"privilegeVersion"`
				PrivilegeOrderId string `json:"privilegeOrderId"`
			} `json:"privilegeLogExtra"`
			Combine struct {
				Padding struct {
					BadgeWidth float64 `json:"badgeWidth"`
					RightPadding float64 `json:"rightPadding"`
					IconTopPadding float64 `json:"iconTopPadding"`
					VerticalPaddingRule float64 `json:"verticalPaddingRule"`
					UseSpecific bool `json:"useSpecific"`
					MiddlePadding float64 `json:"middlePadding"`
					LeftPadding float64 `json:"leftPadding"`
					IconBottomPadding float64 `json:"iconBottomPadding"`
					HorizontalPaddingRule float64 `json:"horizontalPaddingRule"`
				} `json:"padding"`
				FontStyle struct {
					FontSize float64 `json:"fontSize"`
					FontWidth float64 `json:"fontWidth"`
					FontColor string `json:"fontColor"`
					BorderColor string `json:"borderColor"`
				} `json:"fontStyle"`
				BackgroundAutoMirrored bool `json:"backgroundAutoMirrored"`
				IconAutoMirrored bool `json:"iconAutoMirrored"`
				PaddingNewFont struct {
					HorizontalPaddingRule float64 `json:"horizontalPaddingRule"`
					VerticalPaddingRule float64 `json:"verticalPaddingRule"`
					IconTopPadding float64 `json:"iconTopPadding"`
					IconBottomPadding float64 `json:"iconBottomPadding"`
					UseSpecific bool `json:"useSpecific"`
					MiddlePadding float64 `json:"middlePadding"`
					BadgeWidth float64 `json:"badgeWidth"`
					LeftPadding float64 `json:"leftPadding"`
					RightPadding float64 `json:"rightPadding"`
				} `json:"paddingNewFont"`
				DisplayType float64 `json:"displayType"`
				Icon struct {
					UrlListList []string `json:"urlListList"`
					Uri string `json:"uri"`
					Height string `json:"height"`
					Width string `json:"width"`
					AvgColor string `json:"avgColor"`
					ImageType float64 `json:"imageType"`
					OpenWebUrl string `json:"openWebUrl"`
					IsAnimated bool `json:"isAnimated"`
				} `json:"icon"`
				BackgroundDarkMode struct {
					Image struct {
						Uri string `json:"uri"`
						Height string `json:"height"`
						Width string `json:"width"`
						AvgColor string `json:"avgColor"`
						ImageType float64 `json:"imageType"`
						OpenWebUrl string `json:"openWebUrl"`
						IsAnimated bool `json:"isAnimated"`
					} `json:"image"`
					BackgroundColorCode string `json:"backgroundColorCode"`
					BorderColorCode string `json:"borderColorCode"`
				} `json:"backgroundDarkMode"`
				PersonalCardShowStyle float64 `json:"personalCardShowStyle"`
				Str string `json:"str"`
				ProfileCardPanel struct {
					ProjectionConfig struct {
						UseProjection bool `json:"useProjection"`
						Icon struct {
							ImageType float64 `json:"imageType"`
							OpenWebUrl string `json:"openWebUrl"`
							IsAnimated bool `json:"isAnimated"`
							Uri string `json:"uri"`
							Height string `json:"height"`
							Width string `json:"width"`
							AvgColor string `json:"avgColor"`
						} `json:"icon"`
					} `json:"projectionConfig"`
					ProfileContent struct {
						UseContent bool `json:"useContent"`
					} `json:"profileContent"`
					UseNewProfileCardStyle bool `json:"useNewProfileCardStyle"`
					BadgeTextPosition float64 `json:"badgeTextPosition"`
				} `json:"profileCardPanel"`
				Background struct {
					Image struct {
						Width string `json:"width"`
						AvgColor string `json:"avgColor"`
						ImageType float64 `json:"imageType"`
						OpenWebUrl string `json:"openWebUrl"`
						IsAnimated bool `json:"isAnimated"`
						Uri string `json:"uri"`
						Height string `json:"height"`
					} `json:"image"`
					BackgroundColorCode string `json:"backgroundColorCode"`
					BorderColorCode string `json:"borderColorCode"`
				} `json:"background"`
				PublicScreenShowStyle float64 `json:"publicScreenShowStyle"`
				RanklistOnlineAudienceShowStyle float64 `json:"ranklistOnlineAudienceShowStyle"`
				MultiGuestShowStyle float64 `json:"multiGuestShowStyle"`
			} `json:"combine"`
		} `json:"badgeListList"`
		Deprecated29 string `json:"deprecated29"`
	} `json:"user"`
	Icon string `json:"icon"`
	EffectCnt string `json:"effectCnt"`
	Count string `json:"count"`
	Total string `json:"total"`
	Color string `json:"color"`
	SpecifiedDisplayTextList []*struct {
		Uid string `json:"uid"`
		DisplayText struct {
			DefaultFormat struct {
				Italic bool `json:"italic"`
				Weight float64 `json:"weight"`
				ItalicAngle float64 `json:"italicAngle"`
				FontSize float64 `json:"fontSize"`
				UseHeighLightColor bool `json:"useHeighLightColor"`
				UseRemoteClor bool `json:"useRemoteClor"`
				Color string `json:"color"`
				Bold bool `json:"bold"`
			} `json:"defaultFormat"`
			PiecesList []*struct {
				Type float64 `json:"type"`
				StringValue string `json:"stringValue"`
				UserValue struct {
					User struct {
						WithFusionShopEntry bool `json:"withFusionShopEntry"`
						IsFollower bool `json:"isFollower"`
						Status float64 `json:"status"`
						CreateTime string `json:"createTime"`
						Secret float64 `json:"secret"`
						AllowShowMyAction bool `json:"allowShowMyAction"`
						FollowStatus string `json:"followStatus"`
						Deprecated17 bool `json:"deprecated17"`
						PayScore string `json:"payScore"`
						SecUid string `json:"secUid"`
						Deprecated19 bool `json:"deprecated19"`
						BgImgUrl string `json:"bgImgUrl"`
						Deprecated29 string `json:"deprecated29"`
						Deprecated7 string `json:"deprecated7"`
						AllowUseLinkmic bool `json:"allowUseLinkmic"`
						PushFriendAction bool `json:"pushFriendAction"`
						WithCarManagementPermission bool `json:"withCarManagementPermission"`
						DisableIchat float64 `json:"disableIchat"`
						IsFollowing bool `json:"isFollowing"`
						NeedProfileGuide bool `json:"needProfileGuide"`
						Id string `json:"id"`
						IchatRestrictType float64 `json:"ichatRestrictType"`
						AllowStrangeComment bool `json:"allowStrangeComment"`
						Deprecated28 bool `json:"deprecated28"`
						TopVipNo string `json:"topVipNo"`
						LinkMicStats float64 `json:"linkMicStats"`
						Deprecated13 float64 `json:"deprecated13"`
						PushDigg bool `json:"pushDigg"`
						Nickname string `json:"nickname"`
						UserRole float64 `json:"userRole"`
						AllowShowInGossip bool `json:"allowShowInGossip"`
						Constellation string `json:"constellation"`
						PushIchat bool `json:"pushIchat"`
						PushStatus bool `json:"pushStatus"`
						VerifiedReason string `json:"verifiedReason"`
						Deprecated2 float64 `json:"deprecated2"`
						Verified bool `json:"verified"`
						CommentRestrict float64 `json:"commentRestrict"`
						ScmLabel string `json:"scmLabel"`
						Deprecated1 string `json:"deprecated1"`
						Deprecated8 float64 `json:"deprecated8"`
						DisplayId string `json:"displayId"`
						EnableIchatImg string `json:"enableIchatImg"`
						Deprecated5 string `json:"deprecated5"`
						Deprecated18 string `json:"deprecated18"`
						Deprecated16 bool `json:"deprecated16"`
						FanTicketCount string `json:"fanTicketCount"`
						Deprecated3 float64 `json:"deprecated3"`
						Exp float64 `json:"exp"`
						PushCommentStatus bool `json:"pushCommentStatus"`
						PushFollow bool `json:"pushFollow"`
						IdStr string `json:"idStr"`
						PayScores string `json:"payScores"`
						Deprecated4 string `json:"deprecated4"`
						ModifyTime string `json:"modifyTime"`
						ShareQrcodeUri string `json:"shareQrcodeUri"`
						AllowOthersDownloadWhenSharingVideo bool `json:"allowOthersDownloadWhenSharingVideo"`
						PushVideoRecommend bool `json:"pushVideoRecommend"`
						IsBlock bool `json:"isBlock"`
						BioDescription string `json:"bioDescription"`
						Deprecated21 string `json:"deprecated21"`
						BlockStatus float64 `json:"blockStatus"`
						VerifiedContent string `json:"verifiedContent"`
						AllowFindByContacts bool `json:"allowFindByContacts"`
						AllowShareShowProfile bool `json:"allowShareShowProfile"`
						PushVideoPost bool `json:"pushVideoPost"`
						Deprecated6 float64 `json:"deprecated6"`
						SpecialId string `json:"specialId"`
						WithCommercePermission bool `json:"withCommercePermission"`
						Deprecated15 float64 `json:"deprecated15"`
						FoldStrangerChat bool `json:"foldStrangerChat"`
						TicketCount string `json:"ticketCount"`
						Deprecated12 float64 `json:"deprecated12"`
						AllowOthersDownloadVideo bool `json:"allowOthersDownloadVideo"`
						AllowUnfollowerComment bool `json:"allowUnfollowerComment"`
					} `json:"user"`
					WithColon bool `json:"withColon"`
				} `json:"userValue"`
			} `json:"piecesList"`
			Key string `json:"key"`
			DefaultPattern string `json:"defaultPattern"`
		} `json:"displayText"`
	} `json:"specifiedDisplayTextList"`
	LikeEffectList []*struct {
		Version string `json:"version"`
		EffectCnt string `json:"effectCnt"`
		EffectIntervalMs string `json:"effectIntervalMs"`
	} `json:"likeEffectList"`
}
