package msgs
type WebcastSocialMessage struct {
	ShareDisplayStyle string `json:"shareDisplayStyle"`
	ShareCount string `json:"shareCount"`
	Common struct {
		MsgId string `json:"msgId"`
		FoldTypeForWeb string `json:"foldTypeForWeb"`
		ClientSendTime string `json:"clientSendTime"`
		Method string `json:"method"`
		RoomId string `json:"roomId"`
		IsShowMsg bool `json:"isShowMsg"`
		PriorityScore string `json:"priorityScore"`
		MsgProcessFilterK string `json:"msgProcessFilterK"`
		MsgProcessFilterV string `json:"msgProcessFilterV"`
		ToIdc string `json:"toIdc"`
		AnchorPriorityScore string `json:"anchorPriorityScore"`
		Monitor float64 `json:"monitor"`
		DisplayText struct {
			DefaultFormat struct {
				UseRemoteClor bool `json:"useRemoteClor"`
				Color string `json:"color"`
				Bold bool `json:"bold"`
				Italic bool `json:"italic"`
				Weight float64 `json:"weight"`
				ItalicAngle float64 `json:"italicAngle"`
				FontSize float64 `json:"fontSize"`
				UseHeighLightColor bool `json:"useHeighLightColor"`
			} `json:"defaultFormat"`
			PiecesList []*struct {
				Type float64 `json:"type"`
				Format struct {
					Bold bool `json:"bold"`
					Italic bool `json:"italic"`
					Weight float64 `json:"weight"`
					ItalicAngle float64 `json:"italicAngle"`
					FontSize float64 `json:"fontSize"`
					UseHeighLightColor bool `json:"useHeighLightColor"`
					UseRemoteClor bool `json:"useRemoteClor"`
					Color string `json:"color"`
				} `json:"format"`
				StringValue string `json:"stringValue"`
				UserValue struct {
					WithColon bool `json:"withColon"`
					User struct {
						LinkMicStats float64 `json:"linkMicStats"`
						Deprecated21 string `json:"deprecated21"`
						Deprecated15 float64 `json:"deprecated15"`
						AllowOthersDownloadVideo bool `json:"allowOthersDownloadVideo"`
						Deprecated1 string `json:"deprecated1"`
						ShareQrcodeUri string `json:"shareQrcodeUri"`
						Constellation string `json:"constellation"`
						IsFollower bool `json:"isFollower"`
						AllowShareShowProfile bool `json:"allowShareShowProfile"`
						Deprecated3 float64 `json:"deprecated3"`
						VerifiedContent string `json:"verifiedContent"`
						AllowFindByContacts bool `json:"allowFindByContacts"`
						Deprecated29 string `json:"deprecated29"`
						Deprecated12 float64 `json:"deprecated12"`
						BgImgUrl string `json:"bgImgUrl"`
						FanTicketCount string `json:"fanTicketCount"`
						IdStr string `json:"idStr"`
						IsBlock bool `json:"isBlock"`
						CreateTime string `json:"createTime"`
						PayScore string `json:"payScore"`
						FoldStrangerChat bool `json:"foldStrangerChat"`
						UserRole float64 `json:"userRole"`
						CommentRestrict float64 `json:"commentRestrict"`
						PushFollow bool `json:"pushFollow"`
						BadgeListList []*struct {
							DisplayType float64 `json:"displayType"`
							SceneType float64 `json:"sceneType"`
							Position float64 `json:"position"`
							DisplayStatus float64 `json:"displayStatus"`
							ExhibitionType float64 `json:"exhibitionType"`
							PrivilegeLogExtra struct {
								DataVersion string `json:"dataVersion"`
								PrivilegeId string `json:"privilegeId"`
								PrivilegeVersion string `json:"privilegeVersion"`
								PrivilegeOrderId string `json:"privilegeOrderId"`
								Level string `json:"level"`
							} `json:"privilegeLogExtra"`
							Combine struct {
								DisplayType float64 `json:"displayType"`
								PersonalCardShowStyle float64 `json:"personalCardShowStyle"`
								Icon struct {
									Uri string `json:"uri"`
									Height string `json:"height"`
									Width string `json:"width"`
									AvgColor string `json:"avgColor"`
									ImageType float64 `json:"imageType"`
									OpenWebUrl string `json:"openWebUrl"`
									IsAnimated bool `json:"isAnimated"`
									UrlListList []string `json:"urlListList"`
								} `json:"icon"`
								Str string `json:"str"`
								FontStyle struct {
									FontSize float64 `json:"fontSize"`
									FontWidth float64 `json:"fontWidth"`
									FontColor string `json:"fontColor"`
									BorderColor string `json:"borderColor"`
								} `json:"fontStyle"`
								PublicScreenShowStyle float64 `json:"publicScreenShowStyle"`
								RanklistOnlineAudienceShowStyle float64 `json:"ranklistOnlineAudienceShowStyle"`
								MultiGuestShowStyle float64 `json:"multiGuestShowStyle"`
								Background struct {
									BorderColorCode string `json:"borderColorCode"`
									Image struct {
										ImageType float64 `json:"imageType"`
										OpenWebUrl string `json:"openWebUrl"`
										IsAnimated bool `json:"isAnimated"`
										Uri string `json:"uri"`
										Height string `json:"height"`
										Width string `json:"width"`
										AvgColor string `json:"avgColor"`
									} `json:"image"`
									BackgroundColorCode string `json:"backgroundColorCode"`
								} `json:"background"`
								IconAutoMirrored bool `json:"iconAutoMirrored"`
								Padding struct {
									HorizontalPaddingRule float64 `json:"horizontalPaddingRule"`
									VerticalPaddingRule float64 `json:"verticalPaddingRule"`
									MiddlePadding float64 `json:"middlePadding"`
									LeftPadding float64 `json:"leftPadding"`
									IconTopPadding float64 `json:"iconTopPadding"`
									IconBottomPadding float64 `json:"iconBottomPadding"`
									UseSpecific bool `json:"useSpecific"`
									BadgeWidth float64 `json:"badgeWidth"`
									RightPadding float64 `json:"rightPadding"`
								} `json:"padding"`
								ProfileCardPanel struct {
									UseNewProfileCardStyle bool `json:"useNewProfileCardStyle"`
									BadgeTextPosition float64 `json:"badgeTextPosition"`
									ProjectionConfig struct {
										UseProjection bool `json:"useProjection"`
										Icon struct {
											AvgColor string `json:"avgColor"`
											ImageType float64 `json:"imageType"`
											OpenWebUrl string `json:"openWebUrl"`
											IsAnimated bool `json:"isAnimated"`
											Uri string `json:"uri"`
											Height string `json:"height"`
											Width string `json:"width"`
										} `json:"icon"`
									} `json:"projectionConfig"`
									ProfileContent struct {
										UseContent bool `json:"useContent"`
									} `json:"profileContent"`
								} `json:"profileCardPanel"`
								BackgroundDarkMode struct {
									Image struct {
										OpenWebUrl string `json:"openWebUrl"`
										IsAnimated bool `json:"isAnimated"`
										Uri string `json:"uri"`
										Height string `json:"height"`
										Width string `json:"width"`
										AvgColor string `json:"avgColor"`
										ImageType float64 `json:"imageType"`
									} `json:"image"`
									BackgroundColorCode string `json:"backgroundColorCode"`
									BorderColorCode string `json:"borderColorCode"`
								} `json:"backgroundDarkMode"`
								BackgroundAutoMirrored bool `json:"backgroundAutoMirrored"`
								PaddingNewFont struct {
									UseSpecific bool `json:"useSpecific"`
									IconBottomPadding float64 `json:"iconBottomPadding"`
									HorizontalPaddingRule float64 `json:"horizontalPaddingRule"`
									VerticalPaddingRule float64 `json:"verticalPaddingRule"`
									MiddlePadding float64 `json:"middlePadding"`
									BadgeWidth float64 `json:"badgeWidth"`
									LeftPadding float64 `json:"leftPadding"`
									RightPadding float64 `json:"rightPadding"`
									IconTopPadding float64 `json:"iconTopPadding"`
								} `json:"paddingNewFont"`
							} `json:"combine"`
							PriorityType float64 `json:"priorityType"`
							GreyedByClient string `json:"greyedByClient"`
							Openweburl string `json:"openweburl"`
							Display bool `json:"display"`
						} `json:"badgeListList"`
						AllowUnfollowerComment bool `json:"allowUnfollowerComment"`
						PushStatus bool `json:"pushStatus"`
						Deprecated5 string `json:"deprecated5"`
						Deprecated6 float64 `json:"deprecated6"`
						PayGrade struct {
							Score string `json:"score"`
							GradeBanner string `json:"gradeBanner"`
							Deprecated20 string `json:"deprecated20"`
							NextName string `json:"nextName"`
							Deprecated22 string `json:"deprecated22"`
							Deprecated25 string `json:"deprecated25"`
							UpgradeNeedConsume string `json:"upgradeNeedConsume"`
							NextPrivileges string `json:"nextPrivileges"`
							Deprecated24 string `json:"deprecated24"`
							Level string `json:"level"`
							GradeDescribe string `json:"gradeDescribe"`
							Name string `json:"name"`
							Deprecated23 string `json:"deprecated23"`
							Deprecated26 string `json:"deprecated26"`
							ScreenChatType string `json:"screenChatType"`
						} `json:"payGrade"`
						AllowUseLinkmic bool `json:"allowUseLinkmic"`
						PushFriendAction bool `json:"pushFriendAction"`
						PushIchat bool `json:"pushIchat"`
						Secret float64 `json:"secret"`
						Deprecated13 float64 `json:"deprecated13"`
						Deprecated4 string `json:"deprecated4"`
						FollowStatus string `json:"followStatus"`
						Deprecated17 bool `json:"deprecated17"`
						IsFollowing bool `json:"isFollowing"`
						Verified bool `json:"verified"`
						Status float64 `json:"status"`
						SecUid string `json:"secUid"`
						AllowShowInGossip bool `json:"allowShowInGossip"`
						IchatRestrictType float64 `json:"ichatRestrictType"`
						VerifiedReason string `json:"verifiedReason"`
						ScmLabel string `json:"scmLabel"`
						Nickname string `json:"nickname"`
						UserAttr struct {
							IsSuperAdmin bool `json:"isSuperAdmin"`
							MuteDuration string `json:"muteDuration"`
							IsMuted bool `json:"isMuted"`
							IsAdmin bool `json:"isAdmin"`
						} `json:"userAttr"`
						Deprecated28 bool `json:"deprecated28"`
						WithCarManagementPermission bool `json:"withCarManagementPermission"`
						Deprecated2 float64 `json:"deprecated2"`
						AllowShowMyAction bool `json:"allowShowMyAction"`
						Exp float64 `json:"exp"`
						AllowStrangeComment bool `json:"allowStrangeComment"`
						Deprecated16 bool `json:"deprecated16"`
						PushVideoRecommend bool `json:"pushVideoRecommend"`
						Deprecated7 string `json:"deprecated7"`
						FollowInfo struct {
							PushStatus string `json:"pushStatus"`
							FollowingCount string `json:"followingCount"`
							FollowerCount string `json:"followerCount"`
							FollowStatus string `json:"followStatus"`
						} `json:"followInfo"`
						PayScores string `json:"payScores"`
						Id string `json:"id"`
						ModifyTime string `json:"modifyTime"`
						BlockStatus float64 `json:"blockStatus"`
						TicketCount string `json:"ticketCount"`
						DisplayId string `json:"displayId"`
						WithCommercePermission bool `json:"withCommercePermission"`
						Deprecated19 bool `json:"deprecated19"`
						PushCommentStatus bool `json:"pushCommentStatus"`
						AvatarThumb struct {
							AvgColor string `json:"avgColor"`
							ImageType float64 `json:"imageType"`
							OpenWebUrl string `json:"openWebUrl"`
							IsAnimated bool `json:"isAnimated"`
							UrlListList []string `json:"urlListList"`
							Uri string `json:"uri"`
							Height string `json:"height"`
							Width string `json:"width"`
						} `json:"avatarThumb"`
						SpecialId string `json:"specialId"`
						TopVipNo string `json:"topVipNo"`
						PushVideoPost bool `json:"pushVideoPost"`
						AllowOthersDownloadWhenSharingVideo bool `json:"allowOthersDownloadWhenSharingVideo"`
						Deprecated18 string `json:"deprecated18"`
						NeedProfileGuide bool `json:"needProfileGuide"`
						PushDigg bool `json:"pushDigg"`
						Deprecated8 float64 `json:"deprecated8"`
						WithFusionShopEntry bool `json:"withFusionShopEntry"`
						EnableIchatImg string `json:"enableIchatImg"`
						BioDescription string `json:"bioDescription"`
						DisableIchat float64 `json:"disableIchat"`
					} `json:"user"`
				} `json:"userValue"`
			} `json:"piecesList"`
			Key string `json:"key"`
			DefaultPattern string `json:"defaultPattern"`
		} `json:"displayText"`
		FoldType string `json:"foldType"`
		LogId string `json:"logId"`
		RoomMessageHeatLevel string `json:"roomMessageHeatLevel"`
		DispatchStrategy float64 `json:"dispatchStrategy"`
		CreateTime string `json:"createTime"`
		Describe string `json:"describe"`
		AnchorFoldType string `json:"anchorFoldType"`
		FromIdc string `json:"fromIdc"`
		AnchorFoldTypeForWeb string `json:"anchorFoldTypeForWeb"`
	} `json:"common"`
	User struct {
		TopVipNo string `json:"topVipNo"`
		PayScores string `json:"payScores"`
		WithCommercePermission bool `json:"withCommercePermission"`
		BgImgUrl string `json:"bgImgUrl"`
		EnableIchatImg string `json:"enableIchatImg"`
		NeedProfileGuide bool `json:"needProfileGuide"`
		Deprecated1 string `json:"deprecated1"`
		BioDescription string `json:"bioDescription"`
		Deprecated4 string `json:"deprecated4"`
		BadgeListList []*struct {
			Combine struct {
				MultiGuestShowStyle float64 `json:"multiGuestShowStyle"`
				PaddingNewFont struct {
					LeftPadding float64 `json:"leftPadding"`
					RightPadding float64 `json:"rightPadding"`
					IconTopPadding float64 `json:"iconTopPadding"`
					UseSpecific bool `json:"useSpecific"`
					MiddlePadding float64 `json:"middlePadding"`
					BadgeWidth float64 `json:"badgeWidth"`
					IconBottomPadding float64 `json:"iconBottomPadding"`
					HorizontalPaddingRule float64 `json:"horizontalPaddingRule"`
					VerticalPaddingRule float64 `json:"verticalPaddingRule"`
				} `json:"paddingNewFont"`
				Icon struct {
					IsAnimated bool `json:"isAnimated"`
					UrlListList []string `json:"urlListList"`
					Uri string `json:"uri"`
					Height string `json:"height"`
					Width string `json:"width"`
					AvgColor string `json:"avgColor"`
					ImageType float64 `json:"imageType"`
					OpenWebUrl string `json:"openWebUrl"`
				} `json:"icon"`
				Str string `json:"str"`
				Padding struct {
					HorizontalPaddingRule float64 `json:"horizontalPaddingRule"`
					VerticalPaddingRule float64 `json:"verticalPaddingRule"`
					MiddlePadding float64 `json:"middlePadding"`
					BadgeWidth float64 `json:"badgeWidth"`
					RightPadding float64 `json:"rightPadding"`
					IconBottomPadding float64 `json:"iconBottomPadding"`
					UseSpecific bool `json:"useSpecific"`
					LeftPadding float64 `json:"leftPadding"`
					IconTopPadding float64 `json:"iconTopPadding"`
				} `json:"padding"`
				ProfileCardPanel struct {
					UseNewProfileCardStyle bool `json:"useNewProfileCardStyle"`
					BadgeTextPosition float64 `json:"badgeTextPosition"`
					ProjectionConfig struct {
						UseProjection bool `json:"useProjection"`
						Icon struct {
							ImageType float64 `json:"imageType"`
							OpenWebUrl string `json:"openWebUrl"`
							IsAnimated bool `json:"isAnimated"`
							Uri string `json:"uri"`
							Height string `json:"height"`
							Width string `json:"width"`
							AvgColor string `json:"avgColor"`
						} `json:"icon"`
					} `json:"projectionConfig"`
					ProfileContent struct {
						UseContent bool `json:"useContent"`
					} `json:"profileContent"`
				} `json:"profileCardPanel"`
				BackgroundDarkMode struct {
					Image struct {
						AvgColor string `json:"avgColor"`
						ImageType float64 `json:"imageType"`
						OpenWebUrl string `json:"openWebUrl"`
						IsAnimated bool `json:"isAnimated"`
						Uri string `json:"uri"`
						Height string `json:"height"`
						Width string `json:"width"`
					} `json:"image"`
					BackgroundColorCode string `json:"backgroundColorCode"`
					BorderColorCode string `json:"borderColorCode"`
				} `json:"backgroundDarkMode"`
				IconAutoMirrored bool `json:"iconAutoMirrored"`
				FontStyle struct {
					FontSize float64 `json:"fontSize"`
					FontWidth float64 `json:"fontWidth"`
					FontColor string `json:"fontColor"`
					BorderColor string `json:"borderColor"`
				} `json:"fontStyle"`
				Background struct {
					Image struct {
						Uri string `json:"uri"`
						Height string `json:"height"`
						Width string `json:"width"`
						AvgColor string `json:"avgColor"`
						ImageType float64 `json:"imageType"`
						OpenWebUrl string `json:"openWebUrl"`
						IsAnimated bool `json:"isAnimated"`
					} `json:"image"`
					BackgroundColorCode string `json:"backgroundColorCode"`
					BorderColorCode string `json:"borderColorCode"`
				} `json:"background"`
				DisplayType float64 `json:"displayType"`
				BackgroundAutoMirrored bool `json:"backgroundAutoMirrored"`
				PublicScreenShowStyle float64 `json:"publicScreenShowStyle"`
				PersonalCardShowStyle float64 `json:"personalCardShowStyle"`
				RanklistOnlineAudienceShowStyle float64 `json:"ranklistOnlineAudienceShowStyle"`
			} `json:"combine"`
			DisplayType float64 `json:"displayType"`
			PriorityType float64 `json:"priorityType"`
			Position float64 `json:"position"`
			Openweburl string `json:"openweburl"`
			Display bool `json:"display"`
			PrivilegeLogExtra struct {
				PrivilegeOrderId string `json:"privilegeOrderId"`
				Level string `json:"level"`
				DataVersion string `json:"dataVersion"`
				PrivilegeId string `json:"privilegeId"`
				PrivilegeVersion string `json:"privilegeVersion"`
			} `json:"privilegeLogExtra"`
			SceneType float64 `json:"sceneType"`
			DisplayStatus float64 `json:"displayStatus"`
			GreyedByClient string `json:"greyedByClient"`
			ExhibitionType float64 `json:"exhibitionType"`
		} `json:"badgeListList"`
		AllowUseLinkmic bool `json:"allowUseLinkmic"`
		IsFollowing bool `json:"isFollowing"`
		PushFriendAction bool `json:"pushFriendAction"`
		Deprecated17 bool `json:"deprecated17"`
		Secret float64 `json:"secret"`
		Deprecated18 string `json:"deprecated18"`
		DisableIchat float64 `json:"disableIchat"`
		IchatRestrictType float64 `json:"ichatRestrictType"`
		TicketCount string `json:"ticketCount"`
		SecUid string `json:"secUid"`
		PushIchat bool `json:"pushIchat"`
		WithCarManagementPermission bool `json:"withCarManagementPermission"`
		IdStr string `json:"idStr"`
		PushStatus bool `json:"pushStatus"`
		ScmLabel string `json:"scmLabel"`
		CommentRestrict float64 `json:"commentRestrict"`
		FollowStatus string `json:"followStatus"`
		Deprecated29 string `json:"deprecated29"`
		AllowShareShowProfile bool `json:"allowShareShowProfile"`
		AllowStrangeComment bool `json:"allowStrangeComment"`
		PushCommentStatus bool `json:"pushCommentStatus"`
		PushVideoRecommend bool `json:"pushVideoRecommend"`
		AllowUnfollowerComment bool `json:"allowUnfollowerComment"`
		Constellation string `json:"constellation"`
		IsFollower bool `json:"isFollower"`
		Deprecated5 string `json:"deprecated5"`
		AvatarThumb struct {
			Height string `json:"height"`
			Width string `json:"width"`
			AvgColor string `json:"avgColor"`
			ImageType float64 `json:"imageType"`
			OpenWebUrl string `json:"openWebUrl"`
			IsAnimated bool `json:"isAnimated"`
			UrlListList []string `json:"urlListList"`
			Uri string `json:"uri"`
		} `json:"avatarThumb"`
		ModifyTime string `json:"modifyTime"`
		Deprecated21 string `json:"deprecated21"`
		AllowFindByContacts bool `json:"allowFindByContacts"`
		VerifiedReason string `json:"verifiedReason"`
		Deprecated28 bool `json:"deprecated28"`
		Status float64 `json:"status"`
		CreateTime string `json:"createTime"`
		PayGrade struct {
			Score string `json:"score"`
			NextName string `json:"nextName"`
			Level string `json:"level"`
			Deprecated26 string `json:"deprecated26"`
			UpgradeNeedConsume string `json:"upgradeNeedConsume"`
			NextPrivileges string `json:"nextPrivileges"`
			GradeBanner string `json:"gradeBanner"`
			Deprecated20 string `json:"deprecated20"`
			Name string `json:"name"`
			Deprecated22 string `json:"deprecated22"`
			GradeDescribe string `json:"gradeDescribe"`
			Deprecated23 string `json:"deprecated23"`
			Deprecated24 string `json:"deprecated24"`
			Deprecated25 string `json:"deprecated25"`
			ScreenChatType string `json:"screenChatType"`
		} `json:"payGrade"`
		LinkMicStats float64 `json:"linkMicStats"`
		Deprecated13 float64 `json:"deprecated13"`
		Nickname string `json:"nickname"`
		Deprecated7 string `json:"deprecated7"`
		Deprecated8 float64 `json:"deprecated8"`
		FanTicketCount string `json:"fanTicketCount"`
		Id string `json:"id"`
		Deprecated6 float64 `json:"deprecated6"`
		UserRole float64 `json:"userRole"`
		AllowShowInGossip bool `json:"allowShowInGossip"`
		AllowShowMyAction bool `json:"allowShowMyAction"`
		BlockStatus float64 `json:"blockStatus"`
		Exp float64 `json:"exp"`
		Deprecated19 bool `json:"deprecated19"`
		AllowOthersDownloadWhenSharingVideo bool `json:"allowOthersDownloadWhenSharingVideo"`
		PushFollow bool `json:"pushFollow"`
		IsBlock bool `json:"isBlock"`
		Deprecated2 float64 `json:"deprecated2"`
		PayScore string `json:"payScore"`
		DisplayId string `json:"displayId"`
		Deprecated15 float64 `json:"deprecated15"`
		FoldStrangerChat bool `json:"foldStrangerChat"`
		PushVideoPost bool `json:"pushVideoPost"`
		Verified bool `json:"verified"`
		FollowInfo struct {
			FollowStatus string `json:"followStatus"`
			PushStatus string `json:"pushStatus"`
			FollowingCount string `json:"followingCount"`
			FollowerCount string `json:"followerCount"`
		} `json:"followInfo"`
		WithFusionShopEntry bool `json:"withFusionShopEntry"`
		AllowOthersDownloadVideo bool `json:"allowOthersDownloadVideo"`
		Deprecated16 bool `json:"deprecated16"`
		SpecialId string `json:"specialId"`
		PushDigg bool `json:"pushDigg"`
		Deprecated3 float64 `json:"deprecated3"`
		ShareQrcodeUri string `json:"shareQrcodeUri"`
		UserAttr struct {
			IsMuted bool `json:"isMuted"`
			IsAdmin bool `json:"isAdmin"`
			IsSuperAdmin bool `json:"isSuperAdmin"`
			MuteDuration string `json:"muteDuration"`
		} `json:"userAttr"`
		VerifiedContent string `json:"verifiedContent"`
		Deprecated12 float64 `json:"deprecated12"`
	} `json:"user"`
	ShareType string `json:"shareType"`
	Action string `json:"action"`
	ShareTarget string `json:"shareTarget"`
	FollowCount string `json:"followCount"`
}
