package msgs
type WebcastChatMessage struct {
	Content string `json:"content"`
	ContentLanguage string `json:"contentLanguage"`
	FullScreenTextColor string `json:"fullScreenTextColor"`
	InputType float64 `json:"inputType"`
	QuickChatScene float64 `json:"quickChatScene"`
	CommunityFlaggedStatus float64 `json:"communityFlaggedStatus"`
	UserIdentity struct {
		IsModeratorOfAnchor bool `json:"isModeratorOfAnchor"`
		IsAnchor bool `json:"isAnchor"`
		IsGiftGiverOfAnchor bool `json:"isGiftGiverOfAnchor"`
		IsSubscriberOfAnchor bool `json:"isSubscriberOfAnchor"`
		IsMutualFollowingWithAnchor bool `json:"isMutualFollowingWithAnchor"`
		IsFollowerOfAnchor bool `json:"isFollowerOfAnchor"`
	} `json:"userIdentity"`
	Common struct {
		MsgProcessFilterV string `json:"msgProcessFilterV"`
		AnchorFoldTypeForWeb string `json:"anchorFoldTypeForWeb"`
		RoomId string `json:"roomId"`
		IsShowMsg bool `json:"isShowMsg"`
		Describe string `json:"describe"`
		FoldType string `json:"foldType"`
		AnchorFoldType string `json:"anchorFoldType"`
		PriorityScore string `json:"priorityScore"`
		ToIdc string `json:"toIdc"`
		ClientSendTime string `json:"clientSendTime"`
		Method string `json:"method"`
		Monitor float64 `json:"monitor"`
		AnchorPriorityScore string `json:"anchorPriorityScore"`
		FoldTypeForWeb string `json:"foldTypeForWeb"`
		DispatchStrategy float64 `json:"dispatchStrategy"`
		CreateTime string `json:"createTime"`
		MsgProcessFilterK string `json:"msgProcessFilterK"`
		FromIdc string `json:"fromIdc"`
		RoomMessageHeatLevel string `json:"roomMessageHeatLevel"`
		MsgId string `json:"msgId"`
		LogId string `json:"logId"`
	} `json:"common"`
	User struct {
		VerifiedReason string `json:"verifiedReason"`
		Status float64 `json:"status"`
		ModifyTime string `json:"modifyTime"`
		Deprecated21 string `json:"deprecated21"`
		AllowShowInGossip bool `json:"allowShowInGossip"`
		EnableIchatImg string `json:"enableIchatImg"`
		Deprecated29 string `json:"deprecated29"`
		Deprecated17 bool `json:"deprecated17"`
		Nickname string `json:"nickname"`
		Deprecated8 float64 `json:"deprecated8"`
		TicketCount string `json:"ticketCount"`
		AllowFindByContacts bool `json:"allowFindByContacts"`
		UserAttr struct {
			IsMuted bool `json:"isMuted"`
			IsAdmin bool `json:"isAdmin"`
			IsSuperAdmin bool `json:"isSuperAdmin"`
			MuteDuration string `json:"muteDuration"`
		} `json:"userAttr"`
		AllowUseLinkmic bool `json:"allowUseLinkmic"`
		WithCarManagementPermission bool `json:"withCarManagementPermission"`
		AvatarThumb struct {
			AvgColor string `json:"avgColor"`
			ImageType float64 `json:"imageType"`
			OpenWebUrl string `json:"openWebUrl"`
			IsAnimated bool `json:"isAnimated"`
			UrlListList []string `json:"urlListList"`
			Uri string `json:"uri"`
			Height string `json:"height"`
			Width string `json:"width"`
		} `json:"avatarThumb"`
		Verified bool `json:"verified"`
		CreateTime string `json:"createTime"`
		UserRole float64 `json:"userRole"`
		CommentRestrict float64 `json:"commentRestrict"`
		IchatRestrictType float64 `json:"ichatRestrictType"`
		ScmLabel string `json:"scmLabel"`
		ShareQrcodeUri string `json:"shareQrcodeUri"`
		BadgeListList []*struct {
			DisplayType float64 `json:"displayType"`
			SceneType float64 `json:"sceneType"`
			Position float64 `json:"position"`
			DisplayStatus float64 `json:"displayStatus"`
			ExhibitionType float64 `json:"exhibitionType"`
			PrivilegeLogExtra struct {
				DataVersion string `json:"dataVersion"`
				PrivilegeId string `json:"privilegeId"`
				PrivilegeVersion string `json:"privilegeVersion"`
				PrivilegeOrderId string `json:"privilegeOrderId"`
				Level string `json:"level"`
			} `json:"privilegeLogExtra"`
			PriorityType float64 `json:"priorityType"`
			GreyedByClient string `json:"greyedByClient"`
			Openweburl string `json:"openweburl"`
			Display bool `json:"display"`
			Combine struct {
				FontStyle struct {
					FontSize float64 `json:"fontSize"`
					FontWidth float64 `json:"fontWidth"`
					FontColor string `json:"fontColor"`
					BorderColor string `json:"borderColor"`
				} `json:"fontStyle"`
				IconAutoMirrored bool `json:"iconAutoMirrored"`
				Background struct {
					BorderColorCode string `json:"borderColorCode"`
					Image struct {
						Height string `json:"height"`
						Width string `json:"width"`
						AvgColor string `json:"avgColor"`
						ImageType float64 `json:"imageType"`
						OpenWebUrl string `json:"openWebUrl"`
						IsAnimated bool `json:"isAnimated"`
						Uri string `json:"uri"`
					} `json:"image"`
					BackgroundColorCode string `json:"backgroundColorCode"`
				} `json:"background"`
				MultiGuestShowStyle float64 `json:"multiGuestShowStyle"`
				PaddingNewFont struct {
					LeftPadding float64 `json:"leftPadding"`
					IconTopPadding float64 `json:"iconTopPadding"`
					HorizontalPaddingRule float64 `json:"horizontalPaddingRule"`
					VerticalPaddingRule float64 `json:"verticalPaddingRule"`
					IconBottomPadding float64 `json:"iconBottomPadding"`
					UseSpecific bool `json:"useSpecific"`
					MiddlePadding float64 `json:"middlePadding"`
					BadgeWidth float64 `json:"badgeWidth"`
					RightPadding float64 `json:"rightPadding"`
				} `json:"paddingNewFont"`
				Icon struct {
					ImageType float64 `json:"imageType"`
					OpenWebUrl string `json:"openWebUrl"`
					IsAnimated bool `json:"isAnimated"`
					UrlListList []string `json:"urlListList"`
					Uri string `json:"uri"`
					Height string `json:"height"`
					Width string `json:"width"`
					AvgColor string `json:"avgColor"`
				} `json:"icon"`
				BackgroundDarkMode struct {
					BackgroundColorCode string `json:"backgroundColorCode"`
					BorderColorCode string `json:"borderColorCode"`
					Image struct {
						Uri string `json:"uri"`
						Height string `json:"height"`
						Width string `json:"width"`
						AvgColor string `json:"avgColor"`
						ImageType float64 `json:"imageType"`
						OpenWebUrl string `json:"openWebUrl"`
						IsAnimated bool `json:"isAnimated"`
					} `json:"image"`
				} `json:"backgroundDarkMode"`
				PersonalCardShowStyle float64 `json:"personalCardShowStyle"`
				RanklistOnlineAudienceShowStyle float64 `json:"ranklistOnlineAudienceShowStyle"`
				DisplayType float64 `json:"displayType"`
				Str string `json:"str"`
				Padding struct {
					UseSpecific bool `json:"useSpecific"`
					BadgeWidth float64 `json:"badgeWidth"`
					HorizontalPaddingRule float64 `json:"horizontalPaddingRule"`
					VerticalPaddingRule float64 `json:"verticalPaddingRule"`
					IconBottomPadding float64 `json:"iconBottomPadding"`
					MiddlePadding float64 `json:"middlePadding"`
					LeftPadding float64 `json:"leftPadding"`
					RightPadding float64 `json:"rightPadding"`
					IconTopPadding float64 `json:"iconTopPadding"`
				} `json:"padding"`
				ProfileCardPanel struct {
					UseNewProfileCardStyle bool `json:"useNewProfileCardStyle"`
					BadgeTextPosition float64 `json:"badgeTextPosition"`
					ProjectionConfig struct {
						UseProjection bool `json:"useProjection"`
						Icon struct {
							Uri string `json:"uri"`
							Height string `json:"height"`
							Width string `json:"width"`
							AvgColor string `json:"avgColor"`
							ImageType float64 `json:"imageType"`
							OpenWebUrl string `json:"openWebUrl"`
							IsAnimated bool `json:"isAnimated"`
						} `json:"icon"`
					} `json:"projectionConfig"`
					ProfileContent struct {
						UseContent bool `json:"useContent"`
					} `json:"profileContent"`
				} `json:"profileCardPanel"`
				BackgroundAutoMirrored bool `json:"backgroundAutoMirrored"`
				PublicScreenShowStyle float64 `json:"publicScreenShowStyle"`
			} `json:"combine"`
		} `json:"badgeListList"`
		AllowStrangeComment bool `json:"allowStrangeComment"`
		Deprecated18 string `json:"deprecated18"`
		Exp float64 `json:"exp"`
		PushVideoPost bool `json:"pushVideoPost"`
		Deprecated3 float64 `json:"deprecated3"`
		Deprecated5 string `json:"deprecated5"`
		LinkMicStats float64 `json:"linkMicStats"`
		IsFollowing bool `json:"isFollowing"`
		NeedProfileGuide bool `json:"needProfileGuide"`
		PushStatus bool `json:"pushStatus"`
		FollowInfo struct {
			FollowingCount string `json:"followingCount"`
			FollowerCount string `json:"followerCount"`
			FollowStatus string `json:"followStatus"`
			PushStatus string `json:"pushStatus"`
		} `json:"followInfo"`
		DisplayId string `json:"displayId"`
		WithFusionShopEntry bool `json:"withFusionShopEntry"`
		Deprecated19 bool `json:"deprecated19"`
		AllowUnfollowerComment bool `json:"allowUnfollowerComment"`
		Deprecated7 string `json:"deprecated7"`
		Secret float64 `json:"secret"`
		TopVipNo string `json:"topVipNo"`
		PayScore string `json:"payScore"`
		VerifiedContent string `json:"verifiedContent"`
		AllowOthersDownloadWhenSharingVideo bool `json:"allowOthersDownloadWhenSharingVideo"`
		BgImgUrl string `json:"bgImgUrl"`
		FoldStrangerChat bool `json:"foldStrangerChat"`
		Deprecated28 bool `json:"deprecated28"`
		IsFollower bool `json:"isFollower"`
		Id string `json:"id"`
		WithCommercePermission bool `json:"withCommercePermission"`
		Deprecated16 bool `json:"deprecated16"`
		FanTicketCount string `json:"fanTicketCount"`
		FollowStatus string `json:"followStatus"`
		PayScores string `json:"payScores"`
		Deprecated2 float64 `json:"deprecated2"`
		IsBlock bool `json:"isBlock"`
		Deprecated12 float64 `json:"deprecated12"`
		AllowShowMyAction bool `json:"allowShowMyAction"`
		IdStr string `json:"idStr"`
		PushFollow bool `json:"pushFollow"`
		Constellation string `json:"constellation"`
		DisableIchat float64 `json:"disableIchat"`
		PushDigg bool `json:"pushDigg"`
		BioDescription string `json:"bioDescription"`
		Deprecated4 string `json:"deprecated4"`
		PayGrade struct {
			Deprecated22 string `json:"deprecated22"`
			Deprecated23 string `json:"deprecated23"`
			Name string `json:"name"`
			Deprecated24 string `json:"deprecated24"`
			GradeDescribe string `json:"gradeDescribe"`
			UpgradeNeedConsume string `json:"upgradeNeedConsume"`
			NextPrivileges string `json:"nextPrivileges"`
			Deprecated20 string `json:"deprecated20"`
			Level string `json:"level"`
			Deprecated25 string `json:"deprecated25"`
			Deprecated26 string `json:"deprecated26"`
			ScreenChatType string `json:"screenChatType"`
			NextName string `json:"nextName"`
			Score string `json:"score"`
			GradeBanner string `json:"gradeBanner"`
		} `json:"payGrade"`
		SecUid string `json:"secUid"`
		Deprecated15 float64 `json:"deprecated15"`
		AllowOthersDownloadVideo bool `json:"allowOthersDownloadVideo"`
		BlockStatus float64 `json:"blockStatus"`
		PushCommentStatus bool `json:"pushCommentStatus"`
		PushFriendAction bool `json:"pushFriendAction"`
		PushVideoRecommend bool `json:"pushVideoRecommend"`
		Deprecated1 string `json:"deprecated1"`
		Deprecated6 float64 `json:"deprecated6"`
		SpecialId string `json:"specialId"`
		Deprecated13 float64 `json:"deprecated13"`
		AllowShareShowProfile bool `json:"allowShareShowProfile"`
		PushIchat bool `json:"pushIchat"`
	} `json:"user"`
	VisibleToSender bool `json:"visibleToSender"`
	CommentQualityScoresList []*struct {
		Version string `json:"version"`
		Score string `json:"score"`
	} `json:"commentQualityScoresList"`
}
